namespace ProductsApplicationLayer.ViewModals;

using System.Text.Json.Serialization;

public class OllamaGenerateResponse
{
    [JsonPropertyName("model")]
    public string Model { get; set; } = string.Empty;

    [JsonPropertyName("created_at")]
    public DateTime CreatedAt { get; set; }

    // This is the actual text generated by the AI
    [JsonPropertyName("response")]
    public string Response { get; set; } = string.Empty;
    
    // Must be List<long> or long[] to match Ollama's ndJSON format
    [JsonPropertyName("context")]
    public List<long>? Context { get; set; }

    [JsonPropertyName("done")]
    public bool Done { get; set; }
}

